name: Run Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant Execute Permissions from gradlew
        run: chmod +x gradlew

      - name: Run Unit Test
        run: ./gradlew clean testDebug

